-- FIND_ANSWER_ACCORDANCE_BY_QUESTION_ID
SELECT AA.ANSWER_ACCORDANCE_ID, AA.QUESTION_ID, CM.LEFT_SIDE, CM.RIGHT_SIDE
FROM ANSWERS_ACCORDANCE AA INNER JOIN CORRECT_MAPS CM ON AA.ANSWER_ACCORDANCE_ID = CM.ANSWER_ACCORDANCE_ID
WHERE AA.QUESTION_ID = ?;

-- ADD_ANSWER_ACCORDANCE
INSERT INTO ANSWERS_ACCORDANCE (QUESTION_ID) VALUES (?);
INSERT INTO CORRECT_MAPS (LEFT_SIDE, RIGHT_SIDE, ANSWER_ACCORDANCE_ID) VALUES (?, ?, ?);

-- EDIT_ANSWER_ACCORDANCE
UPDATE ANSWERS_ACCORDANCE SET QUESTION_ID = ? WHERE ANSWER_ACCORDANCE_ID = ?;
UPDATE CORRECT_MAPS SET LEFT_SIDE = ?, RIGHT_SIDE = ?, ANSWER_ACCORDANCE_ID = ? WHERE CORRECT_MAP_ID = ?;

-- DELETE_ANSWER_ACCORDANCE
DELETE FROM ANSWERS_ACCORDANCE WHERE ANSWER_ACCORDANCE_ID = ?;
DELETE FROM CORRECT_MAPS WHERE ANSWER_ACCORDANCE_ID = ?;