-- FIND_ANSWER_ACCORDANCE_BY_QUESTION_ID
SELECT * FROM ANSWERS_ACCORDANCE WHERE QUESTION_ID = ?;

-- ADD_ANSWER_ACCORDANCE
INSERT INTO ANSWERS_ACCORDANCE (question_id, left_side_1, right_side_1, left_side_2, right_side_2,
left_side_3, right_side_3, left_side_4, right_side_4)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?);

-- EDIT_ANSWER_ACCORDANCE
UPDATE ANSWERS_ACCORDANCE
SET LEFT_SIDE_1 = ?, RIGHT_SIDE_1 = ?, LEFT_SIDE_2 = ?, RIGHT_SIDE_2 = ?,
LEFT_SIDE_3 = ?, RIGHT_SIDE_3 = ?, LEFT_SIDE_4 = ?, RIGHT_SIDE_4 = ?
WHERE QUESTION_ID = ?;

-- DELETE_ANSWER_ACCORDANCE
DELETE FROM ANSWERS_ACCORDANCE WHERE QUESTION_ID = ?;