-- FIND_GROUP_BY_GROUP_ID
SELECT * FROM GROUPS WHERE GROUP_ID = ?;

-- FIND_GROUPS_BY_AUTHOR_ID
SELECT * FROM GROUPS WHERE AUTHOR_ID = ?;

-- FIND_ALL_GROUPS
SELECT * FROM GROUPS;

-- FIND_GROUPS_NUMBER_BY_AUTHOR_ID
SELECT COUNT(GROUP_ID) FROM GROUPS WHERE AUTHOR_ID = ?;

-- FIND_STUDENTS_NUMBER_IN_GROUP (groupId)
SELECT COUNT(USER_ID) FROM USERS WHERE GROUP_ID IS ?;

-- FIND_ALL_GROUPS_AND_STUDENTS_NUMBER_IN_THEM
SELECT GROUPS.GROUP_ID, GROUPS.NAME, GROUPS.DESCRIPTION,
  GROUPS.CREATION_DATE, GROUPS.AUTHOR_ID, COUNT(USERS.USER_ID)
FROM USERS INNER JOIN GROUPS ON USERS.GROUP_ID = GROUPS.GROUP_ID
WHERE USERS.USER_ROLE = 'STUDENT'
GROUP BY GROUPS.NAME;

-- ADD_GROUP
INSERT INTO GROUPS (NAME, DESCRIPTION, CREATION_DATE, AUTHOR_ID)
VALUES (?, ?, ?, ?);

-- DELETE_GROUP
DELETE FROM GROUPS WHERE GROUP_ID = ?;