-- FIND_QUESTION_BY_ID
SELECT * FROM QUESTIONS WHERE QUESTION_ID = ?;

-- FIND_QUESTIONS_BY_QUIZ_ID
SELECT * FROM QUESTIONS WHERE QUIZ_ID = ?;

-- FIND_QUESTIONS_BY_QUIZ_ID_AND_QUESTION_TYPE
SELECT * FROM QUESTIONS WHERE QUIZ_ID = ? AND QUESTION_TYPE = ?;

-- FIND_QUESTIONS_BY_QUIZ_ID_AND_SCORE
SELECT * FROM QUESTIONS WHERE QUIZ_ID = ? AND SCORE = ?;

-- FIND_QUESTIONS_NUMBER_BY_QUIZ_ID
SELECT COUNT(QUESTION_ID) FROM QUESTIONS WHERE QUIZ_ID = ?;

-- FIND_QUIZ_SCORE_BY_QUIZ_ID
SELECT SUM(SCORE) FROM QUESTIONS WHERE QUIZ_ID = ?;

-- ADD_QUESTION
INSERT INTO QUESTIONS (QUIZ_ID, NAME, BODY, EXPLANATION, QUESTION_TYPE, SCORE)
VALUES (?, ?, ?, ?, ?, ?);

-- TODO: CREATE MORE UPDATE QUERIES
-- EDIT_QUESTION
UPDATE QUESTIONS
SET QUIZ_ID = ?, NAME = ?, BODY = ?, EXPLANATION = ?, QUESTION_TYPE = ?, SCORE = ?
WHERE  QUESTION_ID = ?;

-- DELETE_QUESTION
DELETE FROM QUESTIONS WHERE QUESTION_ID = ?;