-- FIND_USER_BY_USER_ID
SELECT * FROM USERS WHERE USER_ID = ?;

-- FIND_USER_BY_LOGIN
SELECT * FROM USERS WHERE LOGIN = ?;

-- FIND_USER_BY_EMAIL
SELECT * FROM USERS WHERE EMAIL = ?;

-- FIND_USER_BY_PHONE_NUMBER
SELECT * FROM USERS WHERE PHONE_NUMBER = ?;

-- FIND_USER_BY_FIRST_NAME_AND_LAST_NAME
SELECT * FROM USERS WHERE FIRST_NAME = ? AND LAST_NAME = ?;

-- FIND_STUDENTS_BY_GROUP_NAME (groupName)
SELECT *
FROM USERS
WHERE GROUP_ID = (SELECT GROUPS.GROUP_ID FROM GROUPS WHERE GROUPS.NAME = ?) AND USER_ROLE = 'student';

-- FIND_ALL_STUDENTS
SELECT * FROM USERS WHERE USER_ROLE = 'student';

-- FIND_ALL_TEACHERS
SELECT * FROM USERS WHERE USER_ROLE = 'teacher';

-- FIND_ALL_STUDENTS_BY_QUIZ_ID_AND_GROUP_ID (quizId, groupId)
SELECT *
FROM USERS INNER JOIN USER_QUIZ_JUNCTIONS J ON USERS.USER_ID = J.USER_ID
WHERE USERS.USER_ROLE = 'student' AND USERS.GROUP_ID = ? AND J.QUIZ_ID = ?;

-- FIND_STUDENTS_NUMBER
SELECT COUNT(USER_ID) FROM USERS WHERE USER_ROLE = 'student';

-- FIND_TEACHERS_NUMBER
SELECT COUNT(USER_ID) FROM USERS WHERE USER_ROLE = 'teacher';

-- FIND_STUDENTS_NUMBER_IN_GROUP (groupId)
SELECT COUNT(USER_ID) FROM USERS WHERE GROUP_ID = ?;

-- FIND_STUDENTS_NUMBER_IN_GROUP_WITH_CLOSED_QUIZ (groupId, quizId)
SELECT COUNT(USERS.USER_ID)
FROM USERS INNER JOIN USER_QUIZ_JUNCTIONS J ON USERS.USER_ID = J.USER_ID
WHERE USERS.USER_ROLE = 'student' AND USERS.GROUP_ID = ? AND J.QUIZ_ID = ? AND J.QUIZ_STATUS = 'closed';

-- FIND_RESULTS_NUMBER_BY_GROUP_ID_AND_QUIZ_ID (groupId, quizId)
SELECT COUNT(J.RESULT)
FROM USER_QUIZ_JUNCTIONS J INNER JOIN USERS ON J.USER_ID = USERS.USER_ID
WHERE USERS.GROUP_ID = ? AND J.QUIZ_ID = ?;

-- FIND_FINAL_RESULTS_NUMBER_BY_GROUP_ID_AND_QUIZ_ID (groupId, quizId)
SELECT COUNT(J.RESULT)
FROM USER_QUIZ_JUNCTIONS J INNER JOIN USERS ON J.USER_ID = USERS.USER_ID
WHERE USERS.GROUP_ID = ? AND J.QUIZ_ID = ? AND J.QUIZ_STATUS = 'closed';

-- FIND_RESULTS_AND_STUDENT_NAMES_BY_GROUP_ID_AND_QUIZ_ID
SELECT USERS.FIRST_NAME, USERS.LAST_NAME, J.RESULT
FROM USERS INNER JOIN USER_QUIZ_JUNCTIONS J ON USERS.USER_ID = J.USER_ID
WHERE USERS.GROUP_ID = ? AND J.QUIZ_ID = ?;

-- query for method userExists (String login, String email, String phoneNumber)
-- FIND_USER_BY_LOGIN_EMAIL_PHONE_NUMBER
SELECT * FROM USERS WHERE LOGIN = ? AND EMAIL = ? AND PHONE_NUMBER = ?;

-- FIND_USER_BY_LOGIN_AND_PASSWORD
SELECT * FROM USERS WHERE LOGIN = ? AND PASSWORD = ?;

-- ADD_STUDENT_TO_GROUP (userId, groupId)
INSERT INTO USERS (GROUP_ID, FIRST_NAME, LAST_NAME, EMAIL, DATE_OF_BIRTH, PHONE_NUMBER, PHOTO, LOGIN, PASSWORD, USER_ROLE)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?);

-- EDIT_USER

-- DELETE_USER_FROM_GROUP
DELETE FROM USERS WHERE USER_ID = ? AND GROUP_ID = ?;